version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci(action)"
      prefix-development: "ci(dev-action)"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build(docker)"
      prefix-development: "build(docker)"
      include: "scope"
