name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v1.1.0
        with:
          target: patch
          github-token: ${{ secrets.PAT }}
      - uses: ahmadnassri/action-dependabot-auto-merge@v1.1.0
        with:
          target: minor
          github-token: ${{ secrets.PAT }}